# Generated by Django 4.1.7 on 2023-02-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='charliewu@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
