# Generated by Django 4.1.7 on 2023-10-21 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0006_room_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGameSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('NON', 'NONE'), ('TTT', 'TicTacToe'), ('GOA', 'GenerationOfAuthority')], default='TTT', max_length=3)),
                ('player_limit', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_setting', to='chat.room')),
            ],
        ),
    ]
