# Generated by Django 4.1.7 on 2023-10-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_room_game_type'),
        ('basegame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegamesetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_settings', to='chat.room'),
        ),
    ]
