# Generated by Django 4.1.7 on 2023-10-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegame', '0002_alter_basegamesetting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basegamesetting',
            name='user',
        ),
    ]
