# Generated by Django 4.1.7 on 2023-10-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegame', '0003_remove_basegamesetting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegamesetting',
            name='game_type',
            field=models.CharField(choices=[('NON', 'NONE'), ('TTT', 'TicTacToe'), ('GOA', 'GenerationOfAuthority')], default='NON', max_length=3),
        ),
        migrations.AlterField(
            model_name='basegamesetting',
            name='player_limit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
