# Generated by Django 4.1.7 on 2023-10-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegame', '0004_alter_basegamesetting_game_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basegamesetting',
            old_name='player_limit',
            new_name='player_spot',
        ),
    ]
