# Generated by Django 4.1.7 on 2023-10-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegame', '0005_rename_player_limit_basegamesetting_player_spot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basegamesetting',
            old_name='player_spot',
            new_name='player_plot',
        ),
    ]
