# Generated by Django 4.1.7 on 2023-02-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='player',
        ),
    ]
