# Generated by Django 4.1.7 on 2023-02-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_player_options_player_coin'),
        ('chat', '0003_rename_user_message_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='mainpage.player'),
        ),
    ]
