# Generated by Django 4.1.7 on 2023-02-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_player_options_player_coin'),
        ('chat', '0004_alter_message_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='rooms', to='mainpage.player'),
        ),
    ]
