# Generated by Django 4.1.7 on 2023-10-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_room_user_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_type',
            field=models.CharField(choices=[('TTT', 'TicTacToe'), ('GOA', 'GenerationOfAuthority')], default='TTT', max_length=3),
        ),
    ]
