# Generated by Django 4.1.7 on 2023-10-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game_type',
        ),
    ]
