# Generated by Django 4.1.7 on 2023-10-21 03:14

import basegame.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basegame', '0003_remove_basegamesetting_user'),
        ('chat', '0007_remove_room_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_setting',
            field=models.OneToOneField(default=basegame.models.BaseGameSetting.default, on_delete=django.db.models.deletion.PROTECT, to='basegame.basegamesetting'),
        ),
    ]
