# Generated by Django 4.1.7 on 2023-02-19 10:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GOAbasicgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOABasicBoardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_pile_card_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('deck_card_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('deck_card_revealed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('deck_card_seen_by_player_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('player_card_ids', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None)),
                ('current_player_id', models.IntegerField(blank=True, null=True)),
                ('current_turn', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GOABasicGameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('random_seed', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='goabasicgameaction',
            name='test',
        ),
        migrations.AddField(
            model_name='goabasicgameaction',
            name='action_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goabasicgameaction',
            name='action_parameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goabasicgameaction',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GOABasicGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('random_seed', models.IntegerField(blank=True, null=True)),
                ('actions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('game_status', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='GOAbasicgame.goabasicgamestatus')),
            ],
        ),
        migrations.CreateModel(
            name='GOABasicGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(blank=True, null=True)),
                ('played_game_count', models.IntegerField(blank=True, null=True)),
                ('win_game_count', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goa_basic_game_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
