# Generated by Django 4.1.7 on 2023-02-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
        ('GOAbasicgame', '0002_goabasicboardstatus_goabasicgamestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goabasicgameprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goa_basic_game_profile', to='mainpage.player'),
        ),
    ]
