# Generated by Django 4.1.7 on 2023-02-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['nick_name']},
        ),
        migrations.AddField(
            model_name='player',
            name='coin',
            field=models.IntegerField(default=1000),
        ),
    ]
