# Generated by Django 4.1.7 on 2023-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_player_options_player_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_id',
            field=models.CharField(default='starter_1', max_length=50),
        ),
    ]
