# Generated by Django 4.1.7 on 2023-12-14 13:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0003_player_avatar_id'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = []
