# Generated by Django 4.1.7 on 2023-12-14 13:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TTTGame', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='TTTActionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TTTBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), blank=True, null=True, size=None)),
                ('turn', models.IntegerField(default=0)),
                ('turn_of_team', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TTTChoosePositionActionCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTTPlayerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TTTResignActionCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTTSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TTTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_set', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttactionset')),
                ('init_board', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttboard')),
                ('player_set', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttplayerset')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttsetting')),
            ],
        ),
        migrations.CreateModel(
            name='TTTPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(default=0)),
                ('elo', models.IntegerField(default=0)),
                ('played_game_count', models.IntegerField(default=0)),
                ('win_game_count', models.IntegerField(default=0)),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.player')),
                ('player_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='TTTGame.tttplayerset')),
            ],
        ),
        migrations.CreateModel(
            name='TTTGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttboard')),
                ('player_set', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttplayerset')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttsetting')),
            ],
        ),
        migrations.CreateModel(
            name='TTTAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='TTTGame.tttactionset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTTGame.tttplayer')),
            ],
        ),
    ]
