# Generated by Django 5.0.1 on 2024-06-01 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTTGame', '0003_alter_tttboard_turn_alter_tttboard_turn_of_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tttrecord',
            name='player_set',
        ),
        migrations.RemoveField(
            model_name='tttrecord',
            name='setting',
        ),
        migrations.AddField(
            model_name='tttrecord',
            name='game',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttgame'),
            preserve_default=False,
        ),
    ]
