# Generated by Django 5.0.1 on 2024-06-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTTGame', '0004_remove_tttrecord_player_set_remove_tttrecord_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTTSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turns', models.IntegerField(default=1)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TTTGame.tttplayer')),
            ],
        ),
        migrations.AddField(
            model_name='tttrecord',
            name='summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TTTGame.tttsummary'),
        ),
    ]
